import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#1a1a1a',
        paddingTop: 40,
        paddingHorizontal: 16,
        paddingBottom: 80,
    },
    cartItem: {
        backgroundColor: '#333',
        padding: 15,
        marginBottom: 10,
        borderRadius: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    },
    cartItemText: {
        color: '#fff',
        fontSize: 16,
        lineHeight: 22,
    },
    removeText: {
        color: '#000000',
        fontSize: 14,
        marginTop: 5,
        fontWeight: '600',
    },
    actionText: {
        color: '#1E90FF',
        fontSize: 18,
        fontWeight: 'bold',
        marginHorizontal: 10,
    },
    cartActions: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 10,
        justifyContent: 'space-between',
    },
    cartList: {
        paddingBottom: 120,
    },
    emptyCart: {
        color: '#fff',
        fontSize: 18,
        textAlign: 'center',
        marginTop: 20,
    },
    cartFooter: {
        padding: 16,
        backgroundColor: '#fff',
        borderTopWidth: 1,
        borderTopColor: '#ddd',
        alignItems: 'center',
    },
    totalText: {
        fontSize: 20,
        fontWeight: 'bold',
        marginBottom: 15,
        color: '#333',
    },
    checkoutButton: {
        backgroundColor: '#4CAF50',
        paddingVertical: 12,
        paddingHorizontal: 24,
        borderRadius: 8,
        width: '80%',
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 3.84,
        elevation: 5,
    },
    checkoutText: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 16,
        textAlign: 'center',
    },
    actionButton: {
        marginHorizontal: 8,
        backgroundColor: '#ddd',
        padding: 8,
        borderRadius: 4,
        alignItems: 'center',
        justifyContent: 'center',
    },
    removeButton: {
        marginLeft: 16,
        backgroundColor: '#FF4D4D',
        padding: 8,
        borderRadius: 4,
        alignItems: 'center',
        justifyContent: 'center',
    },
});

export default styles;
